<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link rel="stylesheet" type="text/css" href="<%= relativeRoot %>/docs/css/highlightjs.css" media="screen">
    <link rel="stylesheet" type="text/css" href="<%= relativeRoot %>/docs/css/docs.css" media="screen">
    <link rel="stylesheet" type="text/css" href="<%= relativeRoot %>/docs/css/print.css" media="print">
    
    <title>react-datum by Zulily</title>
  </head>

  <!--  This file is generated by scripts/buildDocIndex-->

  <body class="<%= bodyClass %>">
    <script src='<%=relativeRoot %>/dist/vendor/jquery.js'></script>

    <%= header %>

    <div class="main-content">
      <%= content %>
    </div>
  </body>
</html>