<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" type="text/css" href="../syntaxHighlight.css">
  <link rel="stylesheet" type="text/css" href="../example.css">

  <title>react-datum example</title>
</head>

<!--  This file is automatically generated by scripts/buildExamples (`grunt examples`)  -->

<body>
  <div class='code-pane'>
    <%= sourceCode %>
  </div>
  <div class='demo-pane'>
    <h3>Demo:</h3>
    <div id="demo">
      <!--  Example code uses this to render output -->
    </div>
  </div>
  <script src="../../../dist/vendor/jquery.js"></script>
  <script src="../../../dist/vendor/react.js"></script>
  <script src="../../../dist/vendor/react-dom.js"></script>
  <script src="../../../dist/vendor/underscore.js"></script>
  <script src="../../../dist/vendor/backbone.js"></script>
  <script src="../../../dist/react-datum.js"></script>
  <script src="<%= sourceFile %>"></script>

</body>
